wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683097107.737101
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.15.1
      8:
      - 1
      - 5
